In [1]:
import numpy as np
print("---------------------------------Example1------------------------------")
"""
In the following example, one element of specified column from each row of ndarray object is selected. 
Hence, the row index contains all row numbers, and the column index specifies the element to be selected.
"""
x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0, 1, 2], [0, 1, 0]]
print(y)
# The selection includes elements at (0,0), (1,1) and (2,0) from the first array.

print("---------------------------------Example2------------------------------")
"""
n the following example, elements placed at corners of a 4X3 array are selected. 
The row indices of selection are [0,0] and [3,3] whereas the column indices are [0,2] and [0,2].
"""
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])

print('Our array is:')
print(x)
print('\n')

rows = np.array([[0, 0], [3, 3]])
cols = np.array([[0, 2], [0, 2]])
y = x[rows, cols]

print('The corner elements of this array are:')
print(y)

print("---------------------------------Example3------------------------------")
x = np.array([[0,  1,  2], [3,  4,  5], [6,  7,  8], [9, 10, 11]])

print('Our array is:')
print(x)
print('\n')

# slicing
z = x[1:4, 1:3]
# 1:4 -> Selected 1st, 2nd and 3rd position of array, [3,  4,  5], [6,  7,  8], [9, 10, 11]
# 1:3 -> Selected 1st and 2nd position value of those arrays.

print('After slicing, our array becomes:')
print(z)
print('\n')

# using advanced index for column
y = x[1:4, [1, 2]]
# 1:4 -> Selected 1st, 2nd and 3rd position of array, [3,  4,  5], [6,  7,  8], [9, 10, 11]
# [1,2] -> Selected 1st and 2nd position value of those arrays.

print('Slicing using advanced index for column:')
print(y)

print("---------------------------------Example4------------------------------")
"""
Boolean Array Indexing
This type of advanced indexing is used when the resultant object is meant to be the result of 
Boolean operations, such as comparison operators.
"""
x = np.array([[0,  1,  2], [3,  4,  5], [6,  7,  8], [9, 10, 11]])

print('Our array is:')
print(x)
print('\n')

# Now we will print the items greater than 5
print('The items greater than 5 are:')
print(x[x > 5])

print("---------------------------------Example5------------------------------")
# In this example, NaN (Not a Number) elements are omitted by using ~ (complement operator).
a = np.array([np.nan, 1, 2, np.nan, 3, 4, 5])
print(a[~np.isnan(a)])

print("---------------------------------Example6------------------------------")
# The following example shows how to filter out the non-complex elements from an array.
a = np.array([1, 2+6j, 5, 3.5+5j])
print(a[np.iscomplex(a)])

---------------------------------Example1------------------------------
[1 4 5]
---------------------------------Example2------------------------------
Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The corner elements of this array are:
[[ 0  2]
 [ 9 11]]
---------------------------------Example3------------------------------
Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


After slicing, our array becomes:
[[ 4  5]
 [ 7  8]
 [10 11]]


Slicing using advanced index for column:
[[ 4  5]
 [ 7  8]
 [10 11]]
---------------------------------Example4------------------------------
Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The items greater than 5 are:
[ 6  7  8  9 10 11]
---------------------------------Example5------------------------------
[1. 2. 3. 4. 5.]
---------------------------------Example6------------------------------
[2. +6.j 3.5+5.j]
