In [1]:
import numpy as np
"""NumPy package contains an iterator object numpy.nditer. 
It is an efficient multidimensional iterator object using which it is possible to iterate over an array. 
Each element of an array is visited using Python’s standard Iterator interface.
Let us create a 3X4 array using arange() function and iterate over it using nditer."""
print("---------------------Example-1---------------------")
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)

print('Original array is:')
print(a)
print('\n')

print('Modified array is:')
for x in np.nditer(a):
    print(x)

print("---------------------Example-2---------------------")
"""The order of iteration is chosen to match the memory layout of an array,without considering a particular ordering. 
This can be seen by iterating over the transpose of the above array."""
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)

print('Original array is:')
print(a)  # 4*3 and horizontal ordering
print('\n')

print('Transpose(Interchange to 3*4 and vertical) of the original array is:')
b = a.T
print(b)
print('\n')

print('Modified array is:')
for x in np.nditer(b):
    print(x)

print("---------------------Example-3---------------------")
"""Iteration Order
If the same elements are stored using C-style and F-style order, 
the iterator chooses the more efficient way of iterating over an array."""
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print('Original array is:')
print(a)
print('\n')

print('Transpose of the original array is:')
b = a.T
print(b)
print('\n')

print('Sorted in C-style order:')
c = b.copy(order='C')
print(c)
for x in np.nditer(c):
    print(x)

print('\n')

print('Sorted in F-style order:')
c = b.copy(order='F')
print(c)
for x in np.nditer(c):
    print(x)

print("---------------------Example-4---------------------")
"""Modifying Array Values:
The nditer object has another optional parameter called op_flags. 
Its default value is read-only, but can be set to read-write or write-only mode. 
This will enable modifying array elements using this iterator."""
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print('Original array is:')
print(a)
print('\n')

for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = 5*x
print('Modified array is:')
print(a)

print("---------------------Example-5---------------------")
"""In the following example, one-dimensional arrays corresponding to each column is traversed by the iterator."""
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)

print('Original array is:')
print(a)
print('\n')

print('Modified array is:')
for x in np.nditer(a, flags=['external_loop'], order='C'):  # C-style
    print(x)
print('\n')
for x in np.nditer(a, flags=['external_loop'], order='F'):  # F-style
    print(x)

print("---------------------Example-6---------------------")
"""Broadcasting Iteration:
If two arrays are broadcastable, a combined nditer object is able to iterate upon them concurrently. 
Assuming that an array a has dimension 3X4, and 
there is another array b of dimension 1X4, 
the iterator of following type is used (array b is broadcast to size of a)."""
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)

print('First array is:')
print(a)
print('\n')

print('Second array is:')
b = np.array([1, 2, 3, 4], dtype=int)
print(b)
print('\n')

print('Modified array is:')
for x, y in np.nditer([a, b]):
    print("%d:%d" % (x, y))

---------------------Example-1---------------------
Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55
---------------------Example-2---------------------
Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose(Interchange to 3*4 and vertical) of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55
---------------------Example-3---------------------
Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Sorted in C-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
20
40
5
25
45
10
30
50
15
35
55


Sorted in F-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
5
10
15
20
25
30
35
40
45
50
55
---------------------Example-4---------------------
Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 