In [1]:
import numpy as np

print("----------------------Program-1------------------------")
"""
numpy.amin() and numpy.amax()
A DataFrame object has two axes: “axis 0” and “axis 1”. “axis 0” represents rows and “axis 1” represents columns.
“axis 0” = up to down
“axis 1” = left to right
"""
a = np.array([[3, 7, 5], [8, 4, 3], [2, 4, 9]])

print('Our array is:')
print(a)
print('\n')

print('Applying amin() function:')
print(np.amin(a, 1))
print('\n')

print('Applying amin() function again:')
print(np.amin(a, 0))
print('\n')

print('Applying amax() function:')
print(np.amax(a))
print('\n')

print('Applying amax() function again:')
print(np.amax(a, axis=0))

print("----------------------Program-2------------------------")
"""
numpy.ptp()
The numpy.ptp() function returns the range (maximum-minimum) of values along an axis.
in axis, range = (largest value - smallest value)
"""
a = np.array([[3, 7, 5], [8, 4, 3], [2, 4, 9]])

print('Our array is:')
print(a)
print('\n')

print('Applying ptp() function:')
print(np.ptp(a))
print('\n')

print('Applying ptp() function along axis 1:')
print(np.ptp(a, axis=1))
print('\n')

print('Applying ptp() function along axis 0:')
print(np.ptp(a, axis=0))

print("----------------------Program-3------------------------")
"""
numpy.percentile()
Percentile (or a centile) is a measure used in statistics indicating the value below which 
a given percentage of observations in a group of observations fall. 
The function numpy.percentile() takes the following arguments.
numpy.percentile(a, q, axis)
e.g=> output : taking median of ([[30, 40, 70], [80, 20, 10], [50, 90, 60]])
ans-> 50
taking median of ([30, 40, 70])
ans-> 40
"""
a = np.array([[30, 40, 70], [80, 20, 10], [50, 90, 60]])

print('Our array is:')
print(a)
print('\n')

print('Applying percentile() function:')
print(np.percentile(a, 50))
print('\n')

print('Applying percentile() function along axis 1:')
print(np.percentile(a, 50, axis=1))
print('\n')

print('Applying percentile() function along axis 0:')
print(np.percentile(a, 50, axis=0))

print("----------------------Program-4------------------------")
"""
numpy.median()
Median is defined as the value separating the higher half of a data sample from the lower half. 
The numpy.median() function is used as shown in the following program.
"""
a = np.array([[30, 65, 70], [80, 95, 10], [50, 90, 60]])

print('Our array is:')
print(a)
print('\n')

print('Applying median() function:')
print(np.median(a))
print('\n')

print('Applying median() function along axis 0:')
print(np.median(a, axis=0))
print('\n')

print('Applying median() function along axis 1:')
print(np.median(a, axis=1))

print("----------------------Program-5------------------------")
"""
numpy.mean()
Arithmetic mean is the sum of elements along an axis divided by the number of elements. 
The numpy.mean() function returns the arithmetic mean of elements in the array. 
If the axis is mentioned, it is calculated along it.
"""
a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])

print('Our array is:')
print(a)
print('\n')

print('Applying mean() function:')
print(np.mean(a))
print('\n')

print('Applying mean() function along axis 0:')
print(np.mean(a, axis=0))
print('\n')

print('Applying mean() function along axis 1:')
print(np.mean(a, axis=1))

print("----------------------Program-6 Ex-1------------------------")
"""
numpy.average()
Considering an array [1,2,3,4] and corresponding weights [4,3,2,1]
the weighted average is calculated by adding the product of the corresponding elements and 
dividing the sum by the sum of weights.
Weighted average = (1*4+2*3+3*2+4*1)/(4+3+2+1)
"""
a = np.array([1, 2, 3, 4])

print('Our array is:')
print(a)
print('\n')

print('Applying average() function:')
print(np.average(a))
print('\n')

# this is same as mean when weight is not specified
wts = np.array([4, 3, 2, 1])

print('Applying average() function again:')
print(np.average(a, weights=wts))
print('\n')

# Returns the sum of weights, if the returned parameter is set to True.
print('Sum of weights')
print(np.average([1, 2, 3, 4], weights=[4, 3, 2, 1], returned=True))

print("----------------------Program-6 Ex-2------------------------")
a = np.arange(6).reshape(3, 2)

print('Our array is:')
print(a)
print('\n')

print('Modified array:')
wt = np.array([3, 5])
print(np.average(a, axis=1, weights=wt))
print('\n')

print('Modified array:')
print(np.average(a, axis=1, weights=wt, returned=True))

print("----------------------Program-7------------------------")
"""
Standard Deviation:
Standard deviation is the square root of the average of squared deviations from mean. 
The formula for standard deviation is as follows −
std = sqrt(mean(abs(x - x.mean())**2))
If the array is [1, 2, 3, 4], then its mean is 2.5. 
Hence the squared deviations are:-
[1-2.5, 2-2.5, 3-2.5, 4-2.5]
[(-1.5)^2, (-0.5)^2, (-0.5)^2, (1.5)^2]
[2.25, 0.25, 0.25, 2.25]
2.25 + 0.25 + 0.25 + 2.25 = 5
and the square root of its mean divided by 4, i.e., sqrt (5/4) is 1.1180339887498949.
"""
print(np.std([1, 2, 3, 4]))

print("----------------------Program-8------------------------")
"""
Variance:
Variance is the average of squared deviations, i.e., mean(abs(x - x.mean())**2). 
In other words, the standard deviation is the square root of variance.

Here, 5/4 = 1.25
"""
print(np.var([1, 2, 3, 4]))

----------------------Program-1------------------------
Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying amin() function:
[3 3 2]


Applying amin() function again:
[2 4 3]


Applying amax() function:
9


Applying amax() function again:
[8 7 9]
----------------------Program-2------------------------
Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying ptp() function:
7


Applying ptp() function along axis 1:
[4 5 7]


Applying ptp() function along axis 0:
[6 3 6]
----------------------Program-3------------------------
Our array is:
[[30 40 70]
 [80 20 10]
 [50 90 60]]


Applying percentile() function:
50.0


Applying percentile() function along axis 1:
[40. 20. 60.]


Applying percentile() function along axis 0:
[50. 40. 60.]
----------------------Program-4------------------------
Our array is:
[[30 65 70]
 [80 95 10]
 [50 90 60]]


Applying median() function:
65.0


Applying median() function along axis 0:
[50. 90. 60.]


Applying median() function along axis 1:
[65. 80. 60.]
-----