In [1]:
import numpy as np
from numpy import matlib

print("-------------------------Program-1------------------------------")
"""
NumPy package contains a Matrix library numpy.matlib.
This module has functions that return matrices instead of ndarray objects.

matlib.empty()
The matlib.empty() function returns a new matrix without initializing the entries. 
The function takes the following parameters.
"""
a = np.matlib.empty((2, 2))
print(a)

print("-------------------------Program-2------------------------------")
"""
numpy.matlib.zeros()
This function returns the matrix filled with zeros.
"""
print(np.matlib.zeros((2, 2)))

print("-------------------------Program-3------------------------------")
"""
numpy.matlib.ones()
This function returns the matrix filled with 1s.
"""
print(np.matlib.ones((2, 2)))

print("-------------------------Program-4------------------------------")
"""
numpy.matlib.eye()
This function returns a matrix with 1 along the diagonal elements and the zeros elsewhere. 
The function takes the following parameters.

*** Diagonal elements are the elements of square matrix whose row index and column index are same.

numpy.matlib.eye(n, M,k, dtype)
n=The number of rows in the resulting matrix
M=The number of columns, defaults to n
k=Index of diagonal
"""
print(np.matlib.eye(n=4, M=4, k=0, dtype=float))


print("-------------------------Program-5------------------------------")
"""
numpy.matlib.identity()
The numpy.matlib.identity() function returns the Identity matrix of the given size. 
An identity matrix is a square matrix with all diagonal elements as 1.
"""
print(np.matlib.identity(5, dtype=float))

print("-------------------------Program-6------------------------------")
"""
numpy.matlib.rand()
The numpy.matlib.rand() function returns a matrix of the given size filled with random values.
"""
print(np.matlib.rand(3, 3))

print("-------------------------Program-7------------------------------")
i = [[1, 2], [3, 4]]
m = (np.matrix(i))
print(m)

print("-------------------------Program-8------------------------------")
j = np.asarray(i)
print(j)

print("-------------------------Program-9------------------------------")
k = np.asmatrix(i)
print(k)

-------------------------Program-1------------------------------
[[0. 0.]
 [0. 0.]]
-------------------------Program-2------------------------------
[[0. 0.]
 [0. 0.]]
-------------------------Program-3------------------------------
[[1. 1.]
 [1. 1.]]
-------------------------Program-4------------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
-------------------------Program-5------------------------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
-------------------------Program-6------------------------------
[[0.76132661 0.57134038 0.0475845 ]
 [0.68769162 0.2302553  0.07655025]
 [0.84395027 0.17305848 0.84124654]]
-------------------------Program-7------------------------------
[[1 2]
 [3 4]]
-------------------------Program-8------------------------------
[[1 2]
 [3 4]]
-------------------------Program-9------------------------------
[[1 2]
 [3 4]]
