In [1]:
import numpy as np

print("--------------------------program 1------------------------------")
# using array-scalar type

dt = np.dtype(np.int32)
print(dt)

print("----------------------------program 2--------------------------")
# int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4','i8' etc.

dt = np.dtype('i8')
print(dt)

print("-----------------------------program 3-----------------------------")
# The byte order is decided by prefixing '<' or '>' to data type.
# '<' means that encoding is little-endian (least significant is stored in smallest address).
# '>' means that encoding is big-endian (most significant byte is stored in smallest address).
# using endian notation

dt = np.dtype('>i4')
print(dt)

print("-------------------------------program 4-----------------------------------")
# first create structured data type
# The following examples show the use of structured data type.
# Here, the field name and the corresponding scalar data type is to be declared.

dt = np.dtype([('age', np.int8)])
print(dt)

# now apply it to ndarray object

dt = np.dtype([('age', np.int8)])
a = np.array([(10,), (20,), (30,)], dtype=dt)
print(a)

print("-----------------------------program 5--------------------------------")
# file name can be used to access content of age column

dt = np.dtype([('age', np.int8)])
a = np.array([(10,), (20,), (30,)], dtype=dt)
print(a['age'])

print("---------------------------program 6-----------------------------------")
# The following examples define a structured data type called student with a string field 'name',
# an integer field 'age' and a float field 'marks'. This dtype is applied to ndarray object.

student = np.dtype([('name', 'S20'), ('age', 'i1'), ('marks', 'f4')])
print(student)


# Example-
# f is a single-precision floating point number and in your case it uses 4 bytes (4 x 8 = 32 bits). ...
# 'f' is the shorthand for 'float32'. 'f4' also means 'float32' because it has 4 bytes and each byte has 8 bits
# The S1 and S2 strings are data type descriptors;
# the first means the array holds strings of length 1, the second of length 2.
# Python3 is working with Unicode, show "b" when using dtype='S'.
# But using dtype='U' as Unicode, it will give output without "b".

student = np.dtype([('name', 'U20'), ('age', 'i1'), ('marks', 'f4')])
a = np.array([('abc', 21, 50), ('xyz', 18, 75)], dtype=student)
print(a)

print("--------------------------------------program 7--------------------------------------")
# Converting Data Type on Existing Arrays
# The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.
# The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
# The data type can be specified using a string, like 'f' for float, 'i' for integer etc.
# or you can use the data type directly like float for float and int for integer.
print("---------------Example - 1--------------")
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

print("------------Example - 2---------------")
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

print("------------Example - 3--------------")
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

--------------------------program 1------------------------------
int32
----------------------------program 2--------------------------
int64
-----------------------------program 3-----------------------------
>i4
-------------------------------program 4-----------------------------------
[('age', 'i1')]
[(10,) (20,) (30,)]
-----------------------------program 5--------------------------------
[10 20 30]
---------------------------program 6-----------------------------------
[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
[('abc', 21, 50.) ('xyz', 18, 75.)]
--------------------------------------program 7--------------------------------------
---------------Example - 1--------------
[1 2 3]
int32
------------Example - 2---------------
[1 2 3]
int32
------------Example - 3--------------
[ True False  True]
bool
