In [1]:
import numpy as np

print("---------------------------Program 1--------------------------")
# ndarray.shape
# This array attribute returns a tuple consisting of array dimensions.
# It can also be used to resize the array.
# Example1
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)

print("---------------------------Program 2------------------------")
# Example2
# this resize the ndarray
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape = (3, 2)
print(a)

print("--------------------------Program 3------------------------")
# Example3
# NumPy also provides a reshape function to resize an array.
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.reshape(3, 2)
print(b)
# print(b.ndim)

print("-----------------------------Program 4-----------------------")
# ndarray.ndim
# This array attribute returns the number of array dimensions.
# Example1 - this is one dimensional array
a = np.arange(24)
print(a)
# print(a.ndim)

# now reshape it
# b is having three dimensions
b = a.reshape(2, 4, 3)
print(b)
# print(b.ndim)

print("---------------------------Program 5--------------------------")
# numpy.itemsize
# This array attribute returns the length of each element of array in bytes.
# Example1-
# dtype of array is int8 (1 byte)
x = np.array([1, 2, 3, 4, 5], dtype=np.int8)
print(x.itemsize)

print("---------------------------Program 6------------------------")
# Example2-
# dtype of array is now float32 (4 bytes)
x = np.array([1, 2, 3, 4, 5], dtype=np.float32)
print(x.itemsize)

print("----------------------------Program 7--------------------------")
# numpy.flags
# The following example shows the current values of flags.
x = np.array([1, 2, 3, 4, 5])
print(x.flags)

# 1
# C_CONTIGUOUS (C)
#
# The data is in a single, C-style contiguous segment.
#
# 2
# F_CONTIGUOUS (F)
#
# The data is in a single, Fortran-style contiguous segment.
#
# 3
# OWNDATA (O)
#
# The array owns the memory it uses or borrows it from another object.
#
# 4
# WRITEABLE (W)
#
# The data area can be written to. Setting this to False locks the data, making it read-only.
#
# 5
# ALIGNED (A)
#
# The data and all elements are aligned appropriately for the hardware.
#
# 6
# UPDATEIFCOPY (U)
#
# This array is a copy of some other array. When this array is de-allocated,
# the base array will be updated with the contents of this array.
# -------------------------------------------------------------------------------------------------------------------
# Unknown Dimension
# You are allowed to have one "unknown" dimension.

# Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

# Pass -1 as the value, and NumPy will calculate this number for you.

print("----------------Convert 1D array with 8 elements to 3D array with 2x2 elements:------------------------------")

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

# Flattening the arrays
# Flattening array means converting a multidimensional array into a 1D array.
# We can use reshape(-1) to do this.

print("--------------------------------Convert the array into a 1D array:---------------------------------------")

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

---------------------------Program 1--------------------------
(2, 3)
---------------------------Program 2------------------------
[[1 2]
 [3 4]
 [5 6]]
--------------------------Program 3------------------------
[[1 2]
 [3 4]
 [5 6]]
-----------------------------Program 4-----------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
---------------------------Program 5--------------------------
1
---------------------------Program 6------------------------
4
----------------------------Program 7--------------------------
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

----------------Convert 1D array with 8 elements to 3D array with 2x2 elements:------------------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
--------------------------------Conv