In [1]:
import numpy as np

"""The following code shows an example of an empty array."""

print("------------------Program1------------------------")
# Note − The elements in an array show random values as they are not initialized.
x = np.empty([3, 2], dtype=int)
print(x)

"""Returns a new array of specified size, filled with zeros."""

print("------------------Program2 Ex1------------------------")
# array of five zeros. Default dtype is float
x = np.zeros(5)
print(x)
print("------------------Program2 Ex2------------------------")
x = np.zeros((5,), dtype=int)
print(x)
print("------------------Program2 Ex3------------------------")
# custom type
x = np.zeros((2, 2), dtype=[('x', 'i4'), ('y', 'i4')])
print(x)

"""Returns a new array of specified size and type, filled with ones."""

print("------------------Program3 Ex1------------------------")
# array of five ones. Default dtype is float
x = np.ones(5)
print(x)
print("------------------Program3 Ex2------------------------")
x = np.ones([2, 2], dtype=int)
print(x)

------------------Program1------------------------
[[4 0]
 [0 0]
 [0 0]]
------------------Program2 Ex1------------------------
[0. 0. 0. 0. 0.]
------------------Program2 Ex2------------------------
[0 0 0 0 0]
------------------Program2 Ex3------------------------
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
------------------Program3 Ex1------------------------
[1. 1. 1. 1. 1.]
------------------Program3 Ex2------------------------
[[1 1]
 [1 1]]
