In [1]:
import numpy as np

"""numpy.asarray
This function is similar to numpy.array except for the fact that it has fewer parameters. 
This routine is useful for converting Python sequence into ndarray.
numpy.asarray(a, dtype = None, order = None)"""
print("--------------------------Program1 Ex1--------------------------------")
# convert list to ndarray
x = [1, 2, 3]
a = np.asarray(x)
print(a)

print("--------------------------Program1 Ex2--------------------------------")
# dtype is set
x = [1, 2, 3]
a = np.asarray(x, dtype=float)
print(a)

print("--------------------------Program1 Ex3--------------------------------")
# ndarray from tuple
x = (1, 2, 3)
a = np.asarray(x)
print(a)

print("--------------------------Program1 Ex4--------------------------------")
# ndarray from list of tuples
# Creating an ndarray from ragged nested sequences
# (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.
# If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
x = [(1, 2, 3), (4, 5)]
a = np.asarray(x, dtype=object)
print(a)
# Creating an ndarray from ragged nested sequences
# (which is a list-or-tuple of lists-or-tuples-or ndarrays with same lengths or shapes) is deprecated.
# If you meant to do this, you don't have to specify 'dtype=object' when creating the ndarray.
x = [(1, 2, 3), (4, 5, 6)]
a = np.asarray(x, dtype=object)
print(a)

--------------------------Program1 Ex1--------------------------------
[1 2 3]
--------------------------Program1 Ex2--------------------------------
[1. 2. 3.]
--------------------------Program1 Ex3--------------------------------
[1 2 3]
--------------------------Program1 Ex4--------------------------------
[(1, 2, 3) (4, 5)]
[[1 2 3]
 [4 5 6]]
