In [1]:
import numpy as np

"""Iterating Arrays
Iterating means going through elements one by one.
As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python."""

print("----------------------------program-1--------------------------------")
# If we iterate on a 1-D array it will go through each element one by one.
arr = np.array([1, 2, 3])

for x in arr:
    print(x)

print("----------------------------program-2--------------------------------")
# Iterate on the elements of the following 2-D array. In a 2-D array it will go through all the rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

print("----------------------------program-3--------------------------------")
# If we iterate on a n-D array it will go through n-1th dimension one by one.
# To return the actual values, the scalars, we have to iterate the arrays in each dimension.
# Iterate on each scalar element of the 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

print("----------------------------program-4--------------------------------")
# Iterating 3-D Arrays
# In a 3-D array it will go through all the 2-D arrays.
# Iterate on the elements of the following 3-D array:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)

# To return the actual values, the scalars, we have to iterate the arrays in each dimension.
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

"""Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations. 
It solves some basic issues which we face in iteration, lets go through it with examples.
Iterating on Each Scalar Element
In basic for loops, iterating through each scalar of an array we need to use n for loops 
which can be difficult to write for arrays with very high dimensionality."""

print("----------------------------program-5--------------------------------")
# Iterate through the following 3-D array:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

"""Iterating Array With Different Data Types
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.
NumPy does not change the data type of the element in-place (where the element is in array) 
so it needs some other space to perform this action, 
that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered']."""

print("----------------------------program-6--------------------------------")
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

print("----------------------------program-7--------------------------------")
# Iterating With Different Step Size
# Iterate through every scalar element of the 2D array skipping 1 element:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

"""Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.
Sometimes we require corresponding index of the element while iterating, 
the ndenumerate() method can be used for those use cases."""

print("----------------------------program-8 Ex1--------------------------------")
# Enumerate on following 1D arrays elements:
arr = np.array([1, 2, 3])

for indx, x in np.ndenumerate(arr):
    print(indx, x)

print("----------------------------program-8 Ex2--------------------------------")
# Enumerate on following 2D array's elements:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for indx, x in np.ndenumerate(arr):
    print(indx, x)

----------------------------program-1--------------------------------
1
2
3
----------------------------program-2--------------------------------
[1 2 3]
[4 5 6]
----------------------------program-3--------------------------------
1
2
3
4
5
6
----------------------------program-4--------------------------------
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12
----------------------------program-5--------------------------------
1
2
3
4
5
6
7
8
----------------------------program-6--------------------------------
b'1'
b'2'
b'3'
----------------------------program-7--------------------------------
1
3
5
7
----------------------------program-8 Ex1--------------------------------
(0,) 1
(1,) 2
(2,) 3
----------------------------program-8 Ex2--------------------------------
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
