In [1]:
import numpy as np

"""numpy.arange
This function returns an ndarray object containing evenly spaced values within a given range. 
The format of the function is as follows −
numpy.arange(start, stop, step, dtype)"""

print("------------------P1 Example-1------------------------")
x = np.arange(5)
print(x)

print("------------------P1 Example-2------------------------")
# dtype set
x = np.arange(5, dtype=float)
print(x)

print("------------------P1 Example-2------------------------")
# start and stop parameters set
x = np.arange(10, 20, 2)
print(x)

"""numpy.linspace
This function is similar to arange() function. In this function, instead of step size, 
the number of evenly spaced values between the interval is specified. 
The usage of this function is as follows −
numpy.linspace(start, stop, num, endpoint, retstep, dtype)"""

print("------------------P2 Example-1------------------------")
x = np.linspace(10, 20, 5)
print(x)

print("------------------P2 Example-2------------------------")
# endpoint set to false
x = np.linspace(10, 20, 5, endpoint=False)
# endpoint True by default, hence the stop value is included in the sequence. If false, it is not included.
print(x)

print("------------------P2 Example-3------------------------")
# find retstep value
# retstep - If true, returns samples and step between the consecutive numbers
x = np.linspace(1, 2, 5, retstep=True)  # retstep here is 0.25
print(x)

"""numpy.logspace
This function returns an ndarray object that contains the numbers that are evenly spaced on a log scale. 
Start and stop endpoints of the scale are indices of the base, usually 10.
numpy.logspace(start, stop, num, endpoint, base, dtype)"""

print("------------------P3 Example-1------------------------")
# default base is 10
a = np.logspace(2, 4, num=10)
print(a)

print("------------------P3 Example-2------------------------")
# set base of log space to 2
a = np.logspace(1, 10, num=10, base=2)
print(a)

------------------P1 Example-1------------------------
[0 1 2 3 4]
------------------P1 Example-2------------------------
[0. 1. 2. 3. 4.]
------------------P1 Example-2------------------------
[10 12 14 16 18]
------------------P2 Example-1------------------------
[10.  12.5 15.  17.5 20. ]
------------------P2 Example-2------------------------
[10. 12. 14. 16. 18.]
------------------P2 Example-3------------------------
(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)
------------------P3 Example-1------------------------
[  100.           166.81005372   278.25594022   464.15888336
   774.26368268  1291.54966501  2154.43469003  3593.8136638
  5994.84250319 10000.        ]
------------------P3 Example-2------------------------
[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
