In [1]:
import numpy as np

"""A Python slice object is constructed by giving start, stop, and step parameters to the built-in slice function.
This slice object is passed to the array to extract a part of array."""
print("----------------------------Example1-----------------------------")
a = np.arange(10)
s = slice(2, 7, 2)
print(a[s])

print("----------------------------Example2-----------------------------")
"""In the above example, an ndarray object is prepared by arange() function. 
Then a slice object is defined with start, stop, and step values 2, 7, and 2 respectively. 
When this slice object is passed to the ndarray, a part of it starting with index 2 up to 7 with a step of 2 is sliced.
The same result can also be obtained by giving the slicing parameters separated by a colon : 
(start:stop:step) directly to the ndarray object."""
a = np.arange(10)
b = a[2:7:2]
print(b)

print("----------------------------Example3-----------------------------")
# slice single item
a = np.arange(10)
b = a[5]
print(b)

print("----------------------------Example4-----------------------------")
# slice items starting from index
a = np.arange(10)
print(a[2:])

print("----------------------------Example5-----------------------------")
# slice items between indexes
a = np.arange(10)
print(a[2:5])

print("----------------------------Example6-----------------------------")
a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
print(a)

# slice items starting from index
print('Now we will slice the array from the index a[1:]')
print(a[1:])

print("----------------------------Example7-----------------------------")
# array to begin with
a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])

print('Our array is:')
print(a)
print('\n')

# this returns array of items in the second column
print('The items in the second column are:')
print(a[..., 1])
print('\n')

# Now we will slice all items from the second row
print('The items in the second row are:')
print(a[1, ...])
print('\n')

# Now we will slice all items from column 1 onwards
print('The items column 1 onwards are:')
print(a[..., 1:])

----------------------------Example1-----------------------------
[2 4 6]
----------------------------Example2-----------------------------
[2 4 6]
----------------------------Example3-----------------------------
5
----------------------------Example4-----------------------------
[2 3 4 5 6 7 8 9]
----------------------------Example5-----------------------------
[2 3 4]
----------------------------Example6-----------------------------
[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]
----------------------------Example7-----------------------------
Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]
